Repository CESARBR/knot-service-source, pull requests merged in 2019-10, with the labels that each got.

#38 Fix schema response type on message_process
  src/msg.c
Labels: area: knotd, bug, priority: high

#52 Fix missing free struct l_timeout
  src/main.c
Labels: area: knotd, enhancement, priority: low

#55 Free timeout downstream to avoid memory leak
  src/msg.c
Labels: area: knotd, priority: low

#56 Fix possibility of memory leak on cloud functions
  src/cloud.c
Labels: area: knotd, bug, priority: medium

#53 Send unregister message when rollback a device
  src/msg.c
Labels: area: knotd, priority: low

#54 Free uuid and token when unauthorized
  src/msg.c
Labels: area: knotd, priority: medium
